config/routes.rb
  
       Blog::Application.routes.draw do     # Generiert ein Set aus 7 Routen für den Controller posts (index create new create show edit destroy (term: rake routes),                          
       resources :posts                     # die das CRUD-Prinzip bedienen - create read update delete (posts_path, new_post_path, post_path(1), edit_post_path(1) )
       get "log_out" => "sessions#destroy", :as => "log_out"
       get "log_in"  => "sessions#new", :as => "log_in"
       get "sign_up" => "users#new", :as => "sign_up"
       root :to => "posts#index"
       resources :users
       resources :sessions
       resources :accounts
       
       
       
       
       
       
       

    root to: 'posts#index', as: 'index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :title
  
  validates :title, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, :uniqueness => { :message => "ist bereits vergeben" }
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content
  
  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, :uniqueness => { :message => "ist bereits vergeben" }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
          attr_accessible :email, 
                          :password, 
                          :password_confirmation,
                          :role,
                          :status,
                          :benutzername,
                          :benutzerkennung,
                          :firma,
                          :anrede,
                          :vorname,
                          :nachname,
                          :strasse,
                          :hausnummer,
                          :postleitzahl,
                          :ort,
                          :land,
                          :zeitzone,
                          :telefon,
                          :mobile,
                          :steuernummer,
                          :geburtsdatum

            attr_accessor :password
              before_save :encrypt_password
  
validates_confirmation_of :password , :message => " Wiederholung fehlgeschlagen"
    validates_presence_of :password, :on => :create, :message => " ist Pflichtangabe"
    validates_presence_of :email , :message => " ist Pflichtangabe"
  validates_uniqueness_of :email
  
    validates_presence_of :strasse, :on => :update, :message => " ist Pflichtangabe"
    validates_presence_of :hausnummer, :on => :update, :message => " ist Pflichtangabe"
    validates_presence_of :postleitzahl, :on => :update, :message => " ist Pflichtangabe"
    validates_presence_of :ort, :on => :update, :message => " ist Pflichtangabe"
    validates_presence_of :land, :on => :update, :message => " ist Pflichtangabe"
    validates_presence_of :zeitzone, :on => :update, :message => " ist Pflichtangabe"
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def index
    @account = Account.all
  end
  
  def show 
    @account = Account.find(params[:id])
    @user = User.all
  end
  
  def new 
    @account = Account.new
  end
  
  def create 
    @account = Account.new(params[:account])
      if @account.save
        redirect_to accounts_path, :notice => "Der Eintrag wurde gespeichert."
      else
        render "new"
    end
  end
  
  def edit
    @account = Account.find(params[:id])
  end
  
  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
         redirect_to accounts_path, :notice => "Gespeichert."
      else
        render "edit"
    end
  end
  
    def destroy 
    @account = Post.find(params[:id])
    @account.destroy
      redirect_to accounts_path, :notice => "Der Eintrag wurde unwiederruflich aus dem System entfernt."
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base # sidewide
  
  protect_from_forgery
  
  helper_method :current_user
  
  private
  
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
                     
  def index # posts_path
    @post = Post.all
  end
  
  def show # post_path - einen individuellen post_path anzeigen
    @post = Post.find(params[:id])
  end
  
  def new # new_post_path - Formular, um einen neuen Post zu erstellen
    @post = Post.new
  end
  
  def create # kein Pfad - kein View - nur Prozess - übernimmt die vom New-Formular übergebenen Daten und übermittelt diese zur Datenbank
    @post = Post.new(params[:post])
      if @post.save
        redirect_to posts_path, :notice => "Der Eintrag wurde gespeichert."
      else
        render "new"
    end
  end
  
  def edit # edit_post_path - Formular Daten aus der Datenbank zu ändern
    @post = Post.find(params[:id])
  end
  
  def update # kein View - nur Prozess - kein Pfad - übernimmt die vom Edit-Formular übergebenen Daten und übermittelt diese zur Datenbank
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
         redirect_to posts_path, :notice => "Gespeichert."
      else
        render "edit"
    end
  end
  
  def destroy # kein View - nur Prozess - kein Pfad - löscht Daten aus der Datenbank
    @post = Post.find(params[:id])
    @post.destroy
      redirect_to posts_path, :notice => "Der Eintrag wurde unwiederruflich aus dem System entfernt."
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to posts_path, :notice => "Logged in!"
    else
     flash.now.alert = "Email oder Passwort sind nicht korrekt."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = User.all 
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find_by_email(:email)
  end

  def create
    @user = User.new(params[:user])
    if @user.save
     redirect_to users_path, :notice => "Signed up!"
    else
     render "new"
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
         redirect_to :back, :notice => "Gespeichert."
      else
        render "edit"
    end
  end
  
  def destroy 
    @user = User.find(params[:id])
    @user.destroy
      redirect_to users_path, :notice => "Gesperrt."
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/konto_helper.rb
module KontoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/edit.html.erb
<% if User.find(session[:user_id]).role == "Superadmin" %> 	
   	<% if action_name == "edit" %>
    
    	<hr /> 
    		
    <% end %>
    
<h1>Konto-Bereich umbenenne</h1>

<hr>

<%= form_for @account do |f| %>

<% if @account.errors.any? %>
<h2>Errors:
	<ul>
		<% @account.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>

	<p>
		<%= f.label :title, "Titel" %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.submit "Update"; %>
	</p>
<% end %>

<hr>

<p><%= link_to "Administration", posts_path %> |
   <%= link_to "Löschen", :post, :confirm => "Sicher?", :method => :delete %>
</p>
    
<% end %>

app/views/accounts/index.html.erb
<% if User.find(session[:user_id]).role == "Superadmin" %>
    	<hr /> 
	
	<h1>Administration</h1>

<% @account.each do |account| %>
	
			<hr>
		        <p>
		        	ID: <%= account.id %> | <%= link_to account.title, account %>
   				 </p>
   				    			
				<small>
					Erstell-Datum: <%= localize(account.created_at, :format => :sample) %>
				</small>
				<p>	
					<%= link_to "Update", edit_account_path(account) %>
				</p>
				
<% end %>
				<hr>
				
				<%= link_to "Neuen Kontobereich", new_account_path %>
<% end %>

app/views/accounts/show.html.erb
	
	<!-- ############ Einstellungen Beginn ####################################################################### -->
	
	<% if controller_name == "accounts" and @account.id >= 10 and @account.id <= 16 %> <!-- Subnav (Einstellungen) -->

		<p id="konto_subnav">
		
       		<%= link_to "Persönliche Daten", account_path(11) %> | <%= link_to "Zusätzliche Rufnummern", account_path(12) %> | <%= link_to "E-Mail-Adresse ändern", account_path(13) %> | <%= link_to "Passwort ändern", account_path(14) %> | <%= link_to "Tarifansage", account_path(15) %> | <%= link_to "Automatische Aufladung", account_path(16) %>
		
		</p>
		
		<h2>
	
			<%= @account.title %>
	
		</h2>
		
	<!-- ############ Einstellungen - Startseite ################################################################### -->
	
		<% if current_page?(:id=> '10') == true and controller_name == "accounts" %>
        
			<p>
		
				Hier können Sie Ihre Persönlichen Daten verwalten, zusätzliche Rufnummern einrichten, Ihre E-Mail-Adresse und Ihr Passwort ändern, Tarifansagen einstellen und eine automatische Aufladung einrichten.
	
			</p>
	
		<%end %>
		
	<!-- ############ Einstellungen - Persönliche Daten ################################################################### -->
		
		<% if current_page?(:id=> '11') == true and controller_name == "accounts" %> <!-- Einstellungen - Persönliche Daten -->
		
		<% if current_user.errors.any? %>
   			<div class="error_messages">
      			<h2>Errors:</h2>
      				<ul>
        				<% for message in current_user.errors.full_messages %>
          					<li><%= message %></li>
        				<% end %>
      				</ul>
    		</div>
  		<% end %>
  
<%= form_for current_user do |f| %>
    	
    <p class="disabled" >
    	<%= f.label :benutzername, "Benutzername" %><br />
    	<%= f.text_field :benutzername, :disabled => true %>
    </p>
    
    <p class="disabled" >
    	<%= f.label :benutzerkennung, "Benutzerkennung" %><br />
    	<%= f.text_field :benutzerkennung, :disabled => true %>
    </p>
    
    <p>
    	<%= f.label :firma, "Firma" %><br />
    	<%= f.text_field :firma %>
    </p>
    
    <p class="disabled" >
    	<%= f.label :anrede, "Anrede" %><br />
    	<%= f.text_field :anrede, :disabled => true %>
    </p>
    
    <p class="disabled" >
    	<%= f.label :vorname, "Vorname" %><br />
    	<%= f.text_field :vorname, :disabled => true %>
    </p>
    
    <p class="disabled" >
    	<%= f.label :nachname, "Nachname" %><br />
    	<%= f.text_field :nachname, :disabled => true %>
    </p>
    
    <p>
    	<%= f.label :strasse, "Strasse*" %><br />
    	<%= f.text_field :strasse %>
    </p>
    
    <p>
    	<%= f.label :hausnummer, "Hausnummer*" %><br />
    	<%= f.text_field :hausnummer %>
    </p>
    
    <p>
    	<%= f.label :postleitzahl, "Postleitzahl*" %><br />
    	<%= f.text_field :postleitzahl %>
    </p>
    
    <p>
    	<%= f.label :ort, "Ort*" %><br />
    	<%= f.text_field :ort %>
    </p>
    
    <p>
    	<%= f.label :land, "Land*" %><br />
    	<%= f.text_field :land %>
    </p>
    
    <p>
    	<%= f.label :zeitzone, "Zeitzone*" %><br />
    	<%= f.text_field :zeitzone %>
    </p>
    
    <p>
    	<%= f.label :telefon, "Telefon" %><br />
    	<%= f.text_field :telefon %>
    </p>
    
    <p >
    	<%= f.label :mobile, "Mobil" %><br />
    	<%= f.text_field :mobile %>
    </p>
    
    <p>
    	<%= f.label :steuernummer, "Steuernummer" %><br />
    	<%= f.text_field :steuernummer %>
    </p>
    
    <p class="disabled" >
    	<%= f.label :geburtsdatum, "Geburtsdatum" %><br />
    	<%= f.text_field :geburtsdatum, :disabled => true %>
    </p>
  
    <p id="submit">
    	<%= f.submit "Update"; %>
    </p>
    
    <p>
    	Alle mit *(Sternchen) markierten Felder sind Pflichtfelder.
    </p>
    
<% end %>

		</p>		  
		
	
		<%end %>
		
	<!-- ############ Einstellungen - Zusätzliche Rufnummern ################################################################### -->
		 
		<% if current_page?(:id=> '12') == true and controller_name == "accounts" %> <!-- Einstellungen - Zusätzliche Rufnummern -->
		
		<p>
		
			Hier können Sie zusätzliche Rufnummern eintragen, mit denen Sie Ayofone nutzen möchten.
	
		</p>		  
		
	
		<%end %>
		
	<!-- ############ Einstellungen - E-Mail-Adresse ändern ################################################################### -->
		
		<% if current_page?(:id=> '13') == true and controller_name == "accounts" %> <!-- Einstellungen - E-Mail-Adresse ändern -->
		
		<p>
		
			E-Mail-Adresse (Formular-Darstellung)
	
		</p>		  
		
	
		<%end %>
		
	<!-- ############ Einstellungen - Passwort ändern #################################################################### -->
		
		<% if current_page?(:id=> '14') == true and controller_name == "accounts" %> <!-- Einstellungen - Passwort ändern  -->
		
		<p>
		
			Passwort (Formular-Darstellung)
	
		</p>		  
		
	
		<%end %>
		
	<!-- ############ Einstellungen - Tarifansage ################################################################### -->
		
		<% if current_page?(:id=> '15') == true and controller_name == "accounts" %> <!-- Einstellungen - Tarifansage -->
		
		<p>
		
			Weltweite Tarife.
	
		</p>		  
		
	
		<%end %>
		
	<!-- ############ Einstellungen - Automatische Aufladung ################################################################### -->
		
		<% if current_page?(:id=> '16') == true and controller_name == "accounts" %> <!-- Einstellungen - Automatische Aufladung -->
		
		<p>
		
			Formular
	
		</p>		  
		
	
		<%end %>
  	
  	<!-- ############ Einstellungen Ende ############################################################### -->
  	
  	<% end %>
  	
  	<!-- ############ Administration  ################################################################## -->
		
		<% if current_page?(:id=> '17') == true %> <!-- Administration -->
		
			<% if current_user.role == "Superadmin" or current_user.role == "Admin" %>
	
				<p>
				
					<%= link_to "Kunden-Information hinzufügen", new_post_path %> |
					<%= link_to "Benutzer verwalten", users_path %>
					
					<% if current_user.role == "Superadmin" %>		
			
						| <%= link_to "Konto-Bereiche verwalten", accounts_path %>
						
    				<% end %>
    			
    			<p>
    				
				<h2>
	
					<%= @account.title %>
	
				</h2>
				
				<% if current_user.role == "Superadmin" %>
				
					<p>
						Hier können die Kunden-Informationen des Kundencenters, die Benutzerdaten und die Konto-Bereiche verwaltet werden.
    				<p>
    					
				<% else %>
				    
				    <p>
						Hier können die Kunden-Informationen des Kundencenters und die Benutzerdaten verwaltet werden.
    				<p>
    				
				<% end %>
				
    		<% end %>
	
		<%end %>
  		
	<!-- ############ Konto Beginn #################################################################### -->

	<% if current_page?(:id=> '1') == true and controller_name == "accounts" %> <!-- Konto - Startseite -->
    
    	<h2>
    	
    		Willkommen in Ihrem persönlichen Konto-Bereich.
    		
   	 	</h2>
    
		<p>
		
			Hier können Sie Ihr Konto aufladen, Ihr persönliches Telefonbuch verwalten, Ihren Ayofone-Phone Service und SMS Service nutzen, Ihre Rechnungen einsehen und Einstellungen vornehmen.
	
		</p>
	
	<%end %>
	
	<!-- ############ So funktioniert's ###################################################################### -->
	
	<% if current_page?(:id=> '2') == true and controller_name == "accounts" %> <!-- Konto - So funktioniert's -->
    
    	<h2>
    	
    		Beispiele
    		
   	 	</h2>
    
		<p>
		
			....
	
		</p>
	
	<%end %>

	<!-- ############ Konto - Tarifübersicht ############################################################## -->
	
	<% if current_page?(:id=> '3') == true and controller_name == "accounts" %> <!-- Konto - Tarifübersicht -->
    
    	<h2>
    	
    		Globale Tarifinformationen
    		
   	 	</h2>
    
		<p>
		
			....
	
		</p>
	
	<%end %>

	<!-- ############ Konto - FAQ ############################################################## -->
	
	<% if current_page?(:id=> '4') == true and controller_name == "accounts" %> <!-- Konto - FAQ -->
    
    	<h2>
    	
    		Häufig gestellte Fragen
    		
   	 	</h2>
    
		<p>
		
			....
	
		</p>
	
	<%end %>
	
  	<!-- ############ Konto Ende ############################################################### -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
			<head>
  				
  				<title>Kundencenter</title>
				
  				<%= stylesheet_link_tag    "application", :media => "all" %>
  				<%= javascript_include_tag "application" %>
  				<%= csrf_meta_tags %>
  
			</head>
	<body>

		<% flash.each do |name, msg| %>
  			
  			<%= content_tag :div, msg, :id => "flash_#{name}" %>
  		
 			<br />

		<% end %>
	
<div>
	
  <% if current_user %>
    

    
    <p id="user_info">
    	
    	Eingeloggt als <b><%= current_user.email %></b> (<%= current_user.role %>) | <b>Kontostand:</b> 20,00 Euro | <b>Ayofone-ID:</b> 123456 |  
    	
    		<% if action_name != "show" or controller_name == "posts" and controller_name != "accounts" %>
			
				<%= link_to "Ihr Konto", account_path(1) %> |
			
			<% end %>
			
    		<% if action_name != "show" and controller_name == "accounts" %>
			
				<%= link_to "Konto", account_path(1) %> |
			
			<% end %>
			
			<% if action_name == "show" and controller_name == "users" or controller_name == "accounts" %>
			
				<%= link_to "Konto verlassen", posts_path %> |
			
			<% end %>
		    
   			<%= link_to "Log out", log_out_path %>
    </p>
    
   	 <% if action_name == "show" and controller_name == "accounts" %>

		<p id="kundencenter_nav">
       			<%= link_to "Startseite", account_path(1) %> | 
       			<%= link_to "So funktioniert's", account_path(2) %> | 
       			<%= link_to "Tarifübersicht", account_path(3) %> | 
       			<%= link_to "FAQ", account_path(4) %> 
       			
   		</p>
    
    	<h1>
    		<% if controller_name == "accounts" %>
    			
    			<% if @account.title != "Konto aufladen" and @account.id > 10 %>
    			
    			Konto - Einstellungen
    			
    			<% end %> 
    			
    			<% if @account.title != "Konto aufladen" and @account.id < 11 %> 
    		
    			Konto - <%= @account.title %>
    			
    			<% else %>
    			
    				<% if @account.id < 10 %> 
    				
    				<%= @account.title %>		
    						
    				<% end %>
    				
    			<% end %>
    			
    		<% end %>
    		
    	</h1>
    	
    	<p id="konto_nav">
       		<%= link_to "Konto aufladen", account_path(5) %> | 
       		<%= link_to "Telefonbuch", account_path(6) %> | 
       		<%= link_to "Phone", account_path(7) %> | 
       		<%= link_to "SMS", account_path(8) %> | 
       		<%= link_to "Rechungen", account_path(9) %> |
       		<span id="einstellungen_link"><%= link_to "Einstellungen", account_path(10) %></span>
       		
            <% if current_user.role == "Superadmin" or current_user.role == "Admin" %> 
            
       			| <span id="admin_link"><%= link_to "Administration", account_path(17) %></span>
       			
       	   <% end %>
       	   
    	</p>
    	
    	
	<% end %>
    
    
    
    
    <% if action_name != "show" or controller_name == "posts" %>
    
    <% end %>
    
  <% end %>
  
	</div>

		<%= yield %>

</body>

</html>

app/views/posts/index.html.erb
<!-- ####################################################################################### Member : -->

	<% if current_user %>
	
    <% if action_name != "show" %>
    
    	<hr /> 
    		
    <% end %>
    
	<h1>Kundencenter</h1>
    	
		<% @post.each do |post| %>
	
			<hr>
		
   				<h2>
   					<%= link_to post.title, post %>
   				</h2>
   				
    				<!-- <p class="content_txt"><pre><%= post.content %></pre></p> -->
    			
						<small>
							Nachricht vom <%= localize(post.created_at, :format => :sample) %>
						</small>
						
<!-- ########################################################################### Superadmin | Admin : -->
						
				<% if current_user.role == "Superadmin" or current_user.role == "Admin" %>	
    				<p>
    		    <% end %>
    				
						<% if current_user.role == "Superadmin" or current_user.role == "Admin" %>
    							<%= link_to "Update", edit_post_path(post) %>
    					<% end %>

<!-- ################################################################################### Superadmin : -->

    					<% if current_user.role == "Superadmin" %>| 
                			<%= link_to "Löschen", post, :confirm => "Sicher?", :method => :delete %>
						<% end %>
						
				<% if current_user.role == "Superadmin" or current_user.role == "Admin" %>	
    				</p>
    		    <% end %>
    		    

		<% end %>
	
<!-- ################################################################################### Logged out : --> 
	
		
	
	<% else %>

		<p>
			<%= link_to "Sign up", new_user_path %> | <%= link_to "Log in", new_session_path %>

		</p>
		
		<hr>
			
		<p>
			Sie sind nicht eingeloggt.
		</p>
		
	<% end %>

app/views/users/index.html.erb
<% if current_user and current_user.role != "Member" %>

   	<% if action_name != "show" %>
    
    	<hr /> 
    		
    <% end %>

		<h1>Benutzer-Liste</h1>
	
	<hr>
	
	<% @user.each do |user| %>
		
		<p>
			Benutzer: <%= user.email %>
		</p>
			
		<% if current_user == "Superadmin" %>
		
			<p>
				Passwort-Hash: <%= user.password_hash %>
	    	</p>
	    
		<% end %>
			
   	    <p>
   	    	Rolle: <%= user.role %>
   	    </p>
   	    
   	    <p>
   	    	Status: 
   	    	
   	    	<% if user.status == "aktiviert" %>
   	    	
   	    		<b class="aktiviert">
   	    			
   	    	<% end %>
   	    	
    	    <% if user.status == "deaktiviert" %>
   	    	
   	    		<b class="deaktiviert">
   	    			
   	    	<% end %>
   	    	
   	    	<% if user.status == "gesperrt" %>
   	    	
   	    		<b class="gesperrt">
   	    			
   	    	<% end %>      
   	    
   	    		<%= user.status %>
   	    	
			</b>
			
		</p>
		
    	<p>
    		<small>
    			Eingerichtet am <%= localize(user.created_at, :format => :sample) %>
    		</small>
    	</p>
    		
    	<% if current_user.role == "Superadmin" or current_user.role == "Admin"  %> 
    	
    		<p>
    			<%= link_to "Update", edit_user_path(user) %>
    	
    	<% end %>	
    	
    	   	
    	<% if user != current_user and current_user.role == "Superadmin" and user.status == "deaktiviert" %> |
           		
           		<%= link_to "Löschen", user, :confirm => "Sicher? Der Datensatz wird vollständig aus dem System entfernt!", :method => :delete %>
        
        <% end %>

    	<% if user == current_user and user.status != "gesperrt"  %> |
        
               Der eingeloggte Benutzer-Account kann nicht gelöscht werden.
        
        <% end %>
        
        	</p>
        	
        		<hr>
		
		<% end %>
		
		<% if current_user.role == "Superadmin" or current_user.role == "Admin" %>

			<p>
				<%= link_to "Benutzer hinzufügen", new_user_path %> |
				<%= link_to "Kundencenter", posts_path %>
    		<p>

    	<% end %>

<% else %>

	<p>Sie sind nicht eingeloggt.

		<hr>

			<%= link_to "Log in", new_session_path %>
	</p>

<% end %>

app/views/users/new.html.erb
<% if !current_user %>
<%= link_to "Log in", new_session_path %>
<hr>
	<h1>Sign in</h1>
  <% else %>
	<h1>Benutzer einrichten</h1>
<% end %>
<hr>

<%= form_for @user do |f| %>
  
  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul class="ul_errors"><b>ERRORS:</b> 
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <br />
      <hr>
    </div>
  <% end %>
  
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password, "Passwort" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Passwort wiederholen"%><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <% if current_user %>
  <% if current_user.role == "Superadmin" %>
    <p>
    <%= f.label :role, "Rolle" %><br />
    <%= f.select(:role, options_for_select([['Superadmin',"Superadmin"], ['Admin',"Admin"], ['Member',"Member"]]) ) %>
  </p>
  <% end %>
    <% if current_user.role == "Admin" %>
    <p>
    <%= f.label :role, "Rolle" %><br />
    <%= f.select(:role, options_for_select([['Admin',"Admin"], ['Member',"Member"]]) ) %>
  </p>
  <% end %>
  <%else%>
   	<%= hidden_field_tag 'user[role]', 'Member' %>
  <% end %>

<% if current_user %>  
  <p><%= f.submit "Einrichten" %></p>
<% else %>
  <p><%= f.submit "Sign in" %></p>
<% end %>

<% end %>

<% if current_user %>
<hr>

	<p>
    	<%= link_to "Benutzer-Index", users_path %> |
    	<%= link_to "Nachrichten-Index", posts_path %>
    <p>
<% end %>

app/views/users/show.html.erb
	<p id="kundencenter_nav">
    	Startseite | So funktioniert's | Tarifübersicht | FAQ | Ayofone-Phone | SMS | Einstellungen | Rechungen | Einstellungen 
    </p>
    
    	<h1>
    		Konto
    	</h1>
    
    <p id="konto_nav">
    	Konto aufladen | Telefonbuch | Einzelverbindungsnachweis | Ayofone-Phone | SMS | Einstellungen | Rechungen | Einstellungen 
    </p>